<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<PlatformTarget>x64</PlatformTarget>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.6" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.6" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="NovitecCameraAPICLR">
			<HintPath>Novitec\NovitecCameraAPICLR.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Novitec\Settings.cs">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Compile>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<None Update="App.config">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="caminfo.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="expschedule.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="NGis\iCarNumber_ex.til">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="NGis\ngis.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="NGis\NgisCar.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="NGis\Ngslib_x86.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\iCarNumber_ex.til">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="NGis\Ngis.cfg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\libcrypto-1_1-x64.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\libcurl.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\libssl-1_1-x64.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\ngis.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\NgisCar.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\Ngslib_x86.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\novaeye-alpr-1.3.1.nve">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\novaeye.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\novaeye.ini">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\NovaUI.Shared.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\NovaUI.WinForms.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\NovitecCameraAPI.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\NovitecCameraAPICLR.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\systemSetting.config">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\tbb12.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\tbbbind_2_5.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Novitec\tbbmalloc.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
