; NovaEye SDK reads the .ini file specified in the first argument of nvt_alpr_initialize() (or ALPR::Initialize() for C++ API).
; If the argument is null or empty, “novaeye.ini” file located in the same folder as novaeye.dll will be read as default.
;
[alpr]
nve_path = novaeye-alpr-1.3.1.nve ; If you enter a relative path, the reference is the dll/ini path.
