<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>86ced2e4-08d4-4a63-8291-5c746bd1d2a9</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Parking.Contracts\Parking.Contracts.csproj" />
    <ProjectReference Include="..\Parking.Central.Data\Parking.Central.Data.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.0" />
  </ItemGroup>
</Project>
